"""add billing columns to buckets

Revision ID: 13c0af6f21f4
Revises: 307fa68a9bd6
Create Date: 2026-04-13 15:06:48.475416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c0af6f21f4'
down_revision: Union[str, None] = '307fa68a9bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('current_storage_bytes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('ingress_bytes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('egress_bytes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('internal_transfer_bytes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'internal_transfer_bytes')
    op.drop_column('buckets', 'egress_bytes')
    op.drop_column('buckets', 'ingress_bytes')
    op.drop_column('buckets', 'current_storage_bytes')
    # ### end Alembic commands ###
