"""add soft delete and request counting

Revision ID: 27d41f48cb50
Revises: 13c0af6f21f4
Create Date: 2026-04-13 15:07:17.910794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d41f48cb50'
down_revision: Union[str, None] = '13c0af6f21f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('count_write_requests', sa.Integer(), server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('count_read_requests', sa.Integer(), server_default='0', nullable=False))
    op.add_column('objects', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'is_deleted')
    op.drop_column('buckets', 'count_read_requests')
    op.drop_column('buckets', 'count_write_requests')
    # ### end Alembic commands ###
