"""add request counting to buckets

Revision ID: dcbbc3f9a88c
Revises: fdf484c7e03b
Create Date: 2026-04-13 15:07:30.061852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcbbc3f9a88c'
down_revision: Union[str, None] = 'fdf484c7e03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('count_write_requests', sa.Integer(), server_default='0', nullable=False))
    op.add_column('buckets', sa.Column('count_read_requests', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'count_read_requests')
    op.drop_column('buckets', 'count_write_requests')
    # ### end Alembic commands ###
