"""add soft delete to s3objects

Revision ID: fdf484c7e03b
Revises: b700dc524b4b
Create Date: 2026-04-13 15:07:14.314020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf484c7e03b'
down_revision: Union[str, None] = 'b700dc524b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3objects', sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s3objects', 'is_deleted')
    # ### end Alembic commands ###
